hlp_msg db 'ý!þ%²S',10
        db 'RÈýÇ¬ýÈÒÈœ€ÈŒŽ‰„œÈ‹‡†Žš‰œ‡†ÆþÈ‘R',10
        db 'RÈýÇ ýÈÒÈœ€ÈŒŽ‰„œÈ‹‡†Žš‰œ‡†ÈŽ‡šÈ¿†Œ‡Ÿ›ÈÑÝÆþÈ‚R',10
        db 'RÈýÇ¼ý³ý¬ý³ýýµµ³ý«ý³ýýµµýÈÒÈœ€ÈŒ„‰‘ÈŽ‡šÈý©½¼§«§¦®ýÈœ‡ÈŸ‰œÈ†œ„È‰Èƒ‘È›È˜š››ŒÆÈÈÈÈR',10
        db 'RÈ³ý¬ýµÒÈ›˜‹Ž›Èœ€Èœ…Èœ‡ÈŸ‰œÈ†ŒšÈ¬§»ÈŠ„‡ŸÈßÆØØÆþÈ|R',10
        db 'RÈ³ý«ýµÒÈ›˜‹Ž›Èœ€Èœ…Èœ‡ÈŸ‰œÈ†ŒšÈ¬§»ÈßÆØØÈ‰†ŒÈ‰Š‡žÈÀ¿†Œ‡Ÿ›ÈÑÝÁþÈlR',10
        db 'RÈ³ýýµÒÈŒ‡È†‡œÈ›€‡ŸÈœ€È˜„›ÈŸ€„ÈŸ‰œ†ÈŽ‡šÈ‰Èƒ‘ÄÈÒÈýÇ¼ÝýþÈuR',10
        db 'RÈýÇ¸ýÈÒÈÈ›„†œÈ…‡ŒÆþÈŸR',10
        db 'RÈýÇ¦ýÈÒÈÈ†žšÈš‰›Èœ€È›‹š†ÈŸ€„Èš†††Èý©½¼§«§¦®ÆýþÈ}R',10
        db 'RÈýÇ­ýÈÒÈÈ…››‰›È†ÈŠ„‰‹ƒÈ‰†ŒÈŸ€œÆþÈR',10
        db 'RÈýÇ£ýÈÒÈÈ›ŒÈƒ‘Š‡‰šŒÄÈŸ€šÈÒþÈ‘R',10
	db 'RÈÈÈÈª„…þÈzýª­ýÈÈ[Èªš›„þÈ{ýªºýþÈlR',10
	db 'RÈÈÈÈ«‰†‰Œ‰ÈÀŽš†‹€ÁþÈrý«®ýÈÈ[È¼‹€‹ƒ‡›„‡ž‰ƒ‰ÈÀœ‹€‹ƒÁþÈiý«²ýþÈlR',10
	db 'RÈÈÈÈ¼‹€‹ƒ‡›„‡ž‰ƒ‰ÈÀ›„‡ž‰ƒÁþÈiý»¤ýÈÈ[È¬‰†…‰šƒþÈyý¬£ýþÈlR',10
	db 'RÈÈÈÈ®†„‰†ŒþÈzý»½ýÈÈ[È®š‰†‹þÈ{ý®ºýþÈlR',10
	db 'RÈÈÈÈ¯š…‰†‘þÈzý¯ºýÈÈ[È †‰š‘þÈzý ½ýþÈlR',10
	db 'RÈÈÈÈ¡œ‰„‘þÈ|ý¡¼ýÈÈ[È¤‰œ†È©…š‹‰þÈtý¤©ýþÈlR',10
	db 'RÈÈÈÈ ‡„„‰†ŒþÈzý¦¤ýÈÈ[È¦‡šžþÈzý¦§ýþÈlR',10
	db 'RÈÈÈÈ¸‡„‰†ŒþÈ{ý¸¤ýÈÈ[È¸‡šœ‰„þÈyý¸§ýþÈlR',10
	db 'RÈÈÈÈ»˜‰†þÈ|ý»¸ýÈÈ[È»ŸŒ†þÈzý»¾ýþÈlR',10
	db 'RÈÈÈÈ»Ÿœ’š„‰†ŒÈÀŽš†‹€ÁþÈmý»®ýÈÈ[È»Ÿœ’š„‰†ŒÈÀš…‰†ÁþÈmý»¯ýþÈlR',10
	db 'RÈÈÈÈ¯š‰œÈªšœ‰†þÈtý½£ýÈÈ[È«š‡‰œ‰Ç»šŠ‰Ç»„‡ž†‰þÈjý±½ýþÈlR',10
        db 'RÈýÇ¢ý³ý¬ýµ³ý«ýµÈÒÈ‰„Ÿ‰‘›È›€‡ŸÈœ€È„›œÈ‡ŽÈ‹‡†Žš‰œ‡†›È‰†ŒÈ˜š‡…˜œÈŽ‡šÈ‰È‹€‡‹ÆÈÈÈR',10
        db 'RÈ³ý¬ýµÒÈ‰„Ÿ‰‘›È›€‡ŸÈœ€È„›œÈŸ€„ÈŠ‡‡œ†È¬§»ÈŠ„‡ŸÈßÆØØþÈ{R',10
        db 'RÈ³ý«ýµÒÈ‰„Ÿ‰‘›È›€‡ŸÈœ€È„›œÈŸ€„ÈŠ‡‡œ†È¬§»ÈßÆÈÀ¿†Œ‡Ÿ›ÈÑÝÁÈ‡šÈ‰Š‡žÆþÈjR',10
        db 'RÈýÇ»ýÈÒÈ†‰Š„Èœ€È„‰›œÈ‹‡†Žš‰œ‡†È„‡‰Œ†ÆþÈ†R',10
        db 'RÈýÇ¥ýÈÒÈ‹›œ‡…’ÈŸ„‹‡…È…››‰›ÆþÈR',10
        db 'RþÈpýÇ¥ÙýÈÅÈ…‡š††È…››‰þÈ‘R',10
        db 'RþÈpýÇ¥ÚýÈÅÈŒ‰‘È…››‰þÈ•R',10        
        db 'RþÈpýÇ¥ÛýÈÅÈž††È…››‰þÈ‘R',10
        db 'RþÈpýÇ¥ÜýÈÅÈ†€œÈ…››‰þÈ“R',10
        db 'RÈýÇ¥³µýÈÒÈŸ€šÈÈ›Èœ€È†…ŠšÈ‡ŽÈœ€È…››‰ÆþÈR',10        
        db 'RÈýÇ«ýÈÒÈ€€œ„€œÈ‹‡„‡šÆþÈšR',10        
        db 'RÈýÇ®ýÈÒÈŒŽ†›Èœ€È‹‡„‡šÈ‡ŽÈœ€ÈŒ›†‰œ‡†›È†Èœ€È‹‡†Žš‰œ‡†›È„›œÆþÈjR',10
        db 'RÈýÇ¯ýÈÈÒÈ›˜˜š››È€‰ŒšÈ…››‰È†Èœ€È‹‡†Žš‰œ‡†È„›œÆþÈyR',10        
        db 'RÈýÇÝýÈÈÒÈ®‡š‹È‰ÈÝØÈ„†È…‡ŒÆþÈ–R',10        
        db 'RÈýÇ§ýÈÈÒÈ«‡…˜‰œŠ„œ‘È…‡ŒÈŸœ€È¿†Œ‡Ÿ›ÈÑÝÈÎÈ¹­¥¥ÆþÈR',10
        db 'RÈýÇ¡ýÈÈÒÈ¬›‰Š„Èœ€ÈŒœÈ…‡ŒÈ†ŒšÈœ€È‹‡†Žš‰œ‡†ÈžŸšÆþÈvR',10
        db 'RÈýÇ¤ýÈÈÒÈ©„Ÿ‰‘›È›€‡ŸÈœ€È‹‡†Žš‰œ‡†È†‰…ÈŒš†Èœ€ÈŠ‡‡œ˜ÆÈÀž†ÈŸœ€ÈÇ¸ÁÈÈÈR',10
        db 'RÈýÇªýÈÈÒÈ¬‡È†‡œÈ‹š‰œÈœ€È€ŒŒ†È©½¼§«§¦®Æ¬©¼ÈŽ„ÄÈš‰›ÈŽÈŽ‡†ŒÆþÈpR',10
        db 'RÈýÇ²ýÈÈÒÈ¤¼È…‡ŒÉÈÀ†‡œÈŽ‡šÈ„‰…š›ÉÁÈýÇ²²ýÈ†žšœÈœ€È„œÈ…‡ŒÆþÈsR',10
        db 'RÈýÇ¾ýÈÈÒÈ›Èº­©¬«§¦®È†›œ‰ŒÈ‡ŽÈº­©¬ÈÀ‰ŒŒÈº­©¬«§¦®È†Èœ€È©½¼§­°­«Æª©¼ÈŽ„ÉÁÈR',10
	db '$þ%²Q',10
        db 'RÈý£­±»þÈ|ýþÈ•R',10
	db '$þ%²Q',10
	db 'RÈý§¦Å¤¡¦­È ­¤¸ÄÈ‡Šœ‰†ŒÈŸœ€Èª©«£»¸©«­Èžš‘Ÿ€šÈ‹˜œÈ†ŒšÈ¼©ªÒÈÈýþÈmR',10
	db '$þ%²Q',10
	db 'RÈý©ºº§¿»È½¸È©¦¬È¤­®¼ÈÈÈý‡†È„†È˜þÈ‘R',10
	db 'RÈýþÈkº¡¯ ¼ÄÈ¬§¿¦ÈÈÈý‡†È„†ÈŒ‡Ÿ†þÈR',10
	db 'RÈý¸©¯­È¬§¿¦þÈpý†œÈ˜‰þÈ“R',10
	db 'RÈý¸©¯­È½¸þÈrý‡†È˜‰È˜þÈ‘R',10
	db 'RÈý­»«©¸­þÈsý™œÈœ€È€„˜ÈŽ„þÈŠR',10
	db 'RÈý»¸©«­þÈtýœ‡„È‹‡„‡šÈÅÈŠÇŸÈ…‡Œ›þÈ„R',10
	db 'RÈý¼©ªþÈvýœ‡„ÈÚÝÇÝØÈ„†›È…‡Œ›þÈ„R',10
        db 'RÈý¡¦»­º¼þÈsý›‰š‹€ÈŽ‡šÈ‰È›œš†þÈ‰R',10
        db 'RÈý¬­¤­¼­þÈsý‹‰†‹„È›‰š‹€È…‡ŒþÈŠR',10
	db '$þ%²Q',10
	db 'RÈý¼ ­È¤¡»¼È§®È«§¦®¡¯»ÄÈ‡Šœ‰†ŒÈŸœ€È»¸©«­È†›œ‰ŒÈ‡ŽÈ‹€‡‡›†È‰È‹‡†Žš‰œ‡†ÒýR',10
	db '$þ%²Q',10
	db 'RÈýª©«£»¸©«­þÈpý›€‡ŸÈœ€È‡†Å„†È€„˜þÈ‡R',10
	db 'RÈý»¸©«­È‡ŽÈ­¦¼­ºþÈký„‡‰ŒÈœ€È€€„€œŒÈ‹‡†Žš‰œ‡†þÈzR',10
        db 'RÈý©ºº§¿»È½¸þÈpý›‹š‡„„È˜È†Èœ€È„›œþÈ‡R',10
        db 'RÈýþÈk¬§¿¦þÈný›‹š‡„„Èœ‡Èœ€È†œÈ‹‡†Žš‰œ‡†È†Èœ€È„›œþÈpR',10
        db 'RÈýþÈk¤­®¼þÈný›€‡ŸÈœ€È›Šš‡˜È‡ŽÈœ€È‹‡†Žš‰œ‡†ÈŽÈ›œ›þÈlR',10
        db 'RÈýþÈkº¡¯ ¼þÈmý›€‡ŸÈœ€È˜˜šÈ„ž„È‡ŽÈœ€Èš‡˜þÈ{R',10
        db 'RÈÀ¡ŽÈ‘‡È‰šÈ†Èœ€È…‰†Èš‡˜È‡šÈœ€š''›È†‡È›ŠÈ„ž„ÄÈœ€È„‰›œÈœŸ‡Èƒ‘›È‰šÈR',10
        db 'RÈÈ›…˜„‘È†‡šŒÈ‰†ŒÈ‰È›€‡šœÈŠ˜È›È…œœŒÁþÈ…R',10
	db 'RÈý §¥­ÈÎÈ¸©¯­È½¸þÈkýœ€ÈŽš›œÈ‹‡†Žš‰œ‡†È‡†Èœ€È›‹š†þÈwR',10
	db 'RÈý­¦¬ÈÎÈ¸©¯­È¬§¿¦þÈjý„‰›œÈ‹‡†Žš‰œ‡†È‡†È›‹š†þÈ€R',10
	db 'RÈý¼©ªþÈvý›€‡ŸÈœ€È€€„€œŒÈ‹‡†Žš‰œ‡†þÈzR',10
        db 'RÈý»¼©ºþÈuý†ŒÈý©½¼§«§¦®ýþÈR',10
	db 'RÈý¸§¡¦¼þÈtý„‡‰ŒÈ‡†„‘Èœ€È‹‡……‡†È˜‰šœþÈƒR',10
        db 'RÈ©†‘È‡œ€šÈƒ‘ÈŒ›†‰œ†È‰È‹‡†Žš‰œ‡†ÄÈ„‡‰Œ›ÈœÄÈŽÈœÈ›œ›ÆþÈoR',10
	db '$þ%²Q',10
	db 'RÈý¼ ­È«§¦®¡¯½º©¼¡§¦È¡¼»­¤®È» §¿­¬ÈŸœ€È¼©ªÈŽš‡…Èœ€È„›œÈ‡ŽÈ‹‡†Žš‰œ‡†›ÒÈÈÈÈýR',10
	db '$þ%²Q',10
        db 'RÈý©ºº§¿»ÒþÈrýþÈœR',10
        db 'RÈý½¸þÈwý›‹š‡„„Èœ€È‹‡†Žš‰œ‡†È˜ÈÀŽÈ„‡†šÈœ€‰†ÈÚÝÈ„†›ÁÈÈÈR',10
        db 'RÈý¬§¿¦þÈuý›‹š‡„„Èœ€È‹‡†Žš‰œ‡†ÈŒ‡Ÿ†ÈÀŽÈ„‡†šÈœ€‰†ÈÚÝÈ„†›ÁÈR',10
        db 'RÈýº¡¯ ¼þÈtý›‹š‡„„Èœ€È‹‡†Žš‰œ‡†Èœ‡Èœ€Èš€œþÈwR',10
        db 'RÈý¤­®¼þÈuý›‹š‡„„Èœ€È‹‡†Žš‰œ‡†Èœ‡Èœ€È„ŽœþÈxR',10
        db 'RÈý §¥­þÈuý‚…˜Èœ‡Èœ€ÈŠ†††È‡ŽÈœ€È„†þÈ{R',10
        db 'RþÈzŽÈ‰†‘È‡ŽÈœ€È›€‡Ÿ†È„†›È‹Œ›ÈÐØÈ‹€‰š‰‹œš›þÈmR',10
	db 'RÈý¸©¯­È¬§¿¦þÈpý†œÈ‹‡†Žš‰œ‡†þÈŠR',10
	db 'RÈý¸©¯­È½¸þÈrý˜šž‡›È‹‡†Žš‰œ‡†È†È„›œþÈ~R',10
	db 'RÈý¼©ªÄÈ­»«þÈqýšœš†Èœ‡Èœ€È„›œÈ‡ŽÈ‹‡†Žš‰œ‡†›þÈxR',10
	db 'RÈý»¸©«­þÈtýœ‡„È‹‡„‡šÈÅÈŠÇŸÈ…‡Œ›þÈ„R',10
	db 'RÈý­¦¼­ºþÈtý‹€‡‡›Èœ€È›€‡Ÿ†È‹‡†Žš‰œ‡†þÈ~R',10
        db 'RÈý¸§¡¦¼ÈÀÆÁþÈpý„‡‰ŒÈ‡†„‘Èœ€È‹‡……‡†È˜‰šœÄÈ‰ŽœšÈ¬­¾¡«­ÕÌþÈsR',10
        db 'RÈýª©«£»¸©«­þÈpý›€‡ŸÈœ€È‡†Å„†È€„˜þÈ‡R',10
        db 'RÈý­ÈÀ­Èƒ‘ÁþÈpý†‰Š„ÇŒ›‰Š„È„†ÈŒœ†È…‡ŒþÈ|R',10
        db 'RÈýÈÈ»¸©«­È†È''­''È…‡ŒÈÈý†‰Š„ÇŒ›‰Š„È‰È„†þÈ‡R',10
        db 'RÈýþÈj×È†È''­''È…‡ŒÈÈý†‰Š„ÇŒ›‰Š„È‹œÈœ€È„†È˜š‡…˜œþÈvR',10
	db '$þ%²Q',10
        db 'RÈý©½¼§«§¦®ýÄÈžš›‡†ÈÙÆÙÈœ‡Èœ€›È„‰œœšÄÈ‰„„Èžš›‡†›È‡ŽÈýº­©¬«§¦®ýÄÈýýºý­ý©ý¬ýÈ‰†ŒÈÈÈÈR',10
        db 'RÈýª§§¼¡¼ýÈ‰šÈœ€È˜š‡˜šœ‘È‡ŽÈÀ…ÁÒþÈ‘R',10
        db 'RÈýþ4oÈý¬‡Šš‡žƒ†È¬‰†„þÈkýþÈŒR',10
        db 'RÈý3333ü333ý3333ÈýÙÙÄÈ‹€ÆÈŒÈ„‰È«„‰šbšÈýþÈR',10
	db 'RÈý33üþ3ký33ÈýÙÚØßÈ¯†bžÄþÈpýþÈR',10
	db 'RÈý3333ü333ý3333Èý»››þÈvýþÈR',10
        db 'RÈýþ7oÈýœ„ÈÎÈŽ‰ÒÈÜÙÈÚÚÈÅÈßÛÝÈÞÑÈÜßþÈkýþÈ‚R',10
        db 'RÈý…‰„ÒÈŒŠ„‡‹ƒ¨†Ž‡…‰†‰ƒÆ‹€þÈzýþÈ€R',10
	db '$þ%²Q',10
	db 'RÈý©½¼§«§¦®ýÈŸ‰›È‡š†‰„„‘È˜š‡š‰……ŒÈŠ‘È‰ÈŽš†‹€È‹‡ŒšÈŸ€‹€È›È†ƒ†‡Ÿ†Èœ‡È…ÆÈR',10
	db 'RÈ©Èžš›‡†ÄÈœ€‰œÈ¡È›ŒÈ‰›Èœ€È††È‡ŽÈý©½¼§«§¦®ýÈŸ‰›È˜Š„›€ŒÈ†È‰È»¾¥ÄþÈiR',10
	db 'RÈ›žš‰„È‘‰š›È‰‡ÆÈÑØÍÈ‡ŽÈœ€È‡š†‰„È˜š‡š‰…ÄÈ€‰žÈŠ†È…‡ŒŽŒÆÈ¼€È†‰…ÈR',10
        db 'RÈ€‰›È†‡œÈŠ†È‹€‰†ŒÆþÈœR',10
	db '$þ%²Q',10
        db 'RÈ¡Èœ€‰†ƒÈ‰„„Èœ€ÈŠœ‰Èœ›œš›È‰†ŒÈ‰„„Èœ€‡›ÈŸ€‡Èœ‡‡ƒÈ‰†‘È˜‰šœÈ†Èœ€ÈŒž„‡˜ÅÈR',10
	db 'RÈ˜…†œÈ‡ŽÈœ€›È›‡ŽœŸ‰šÆþÈ™R',10
	db '$þ%²Q',10
	db 'RÈý©„„Èœ€È†‰…›È‡ŽÈ‹‡…˜‰†›ÄÈ‰›ÈŸ„„È‰›Èœ€šÈ˜š‡Œ‹œ›È‰šÈœ€Èœš‰Œ…‰šƒ›È‡ŽÈÈýR',10
        db 'RÈýœ€šÈš›˜‹œŽÈ‡Ÿ†š›ÆþÈ€ýþÈ~R',10
	db ' þ%²T',10
	db 'ý³þÈ‚†ŒÈ‡ŽÈ€„˜þÈ‰'
			     
ended                db 'üYÈ©½¼§«§¦®ÈÛÆØÈŠœ‰ÈÚÈþYn½Y¦Y¬Y­YºYYY«Y§Y¦Y»Y¼YºY½Y«Y¼Y¡Y§Y¦þYl',10,'ÿ'
press_a_extended_key db 'ý?³ýÈÈý?„†ýÈ §¥­Èý?Š†††ýÈ­¦¬Èý?ÈýÈ¸½˜È¸¬†Èý?˜‰ýÈ­»¸©«­Èý?‹‡„‡šÇŠÎŸýÈ¼©ªÈý?ÝØÇÚÝýÈ­»«Èý?µ'
search_stupid_msg    db 'ýÈÈ»‰š‹€ÒÈÈ³ý'
                     db 67 dup ('È')
                     db 'ýµ'
press_search         db 'ý³È%Õ%ÕÈ»‰š‹€†ÆÆÆ%Õ%Õ%ÕÕ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%Õ%ÕÈµ' 

linemsg         db      'ý³ÈýÈ›‹š‡„„È„ŽœÈýýÈ˜ÈýýÈŒ‡Ÿ†ÈýýÈš€œÈý §¥­Èý„Žœ…‡›œÈ˜‡›œ‡†ÈýÆÈý‡†„‘È‹‡……‡†È˜‰šœÈýµ',10
                db      'ý³È¸‰½˜ýÈ˜šž‡›È‹‡†ŽÈý¸‰¬†ýÈ†œÈ‹‡†ŽÈý¼©ªÇ­»«ýÈšœš†Èý»¸©«­Èý‹‡„‡šÈÅÈŠÇŸÈÈýµ',10,'ÿ'

linemsg2        db      'ý³Èýý¤ý¡ý¦ý­ýÈÅÈ†‰Š„ÇŒ›‰Š„È‡†È„†Èžš›‡†ÈÙÆÙÈÈÈÀ‹ÁÈ¬‰†„È¬‡Šš‡žƒ†ÈÅÈÙÑÑÝÈýµ',10
                db      'ý³ÈýŒ‡Ÿ†ýÈÈý˜ýÈ­Èý…‡ŒýÈ¸½˜Èý†œÈ‹†ŽÈýÈ¸¬†Èý˜šž‡›È‹†ŽýÈ»¸©«­Èý†ÇŒ›‰Š„È„†ÈýÈ×Èµ',10,'ÿ'

slam_key_msg    db      'ý»„‰…È‰†‘Èƒ‘Èœ‡È‹‡†œ†ÆÆÆÈýÿ'
menucolormsg    db      'ý¥­¦½«§¤§ºÈýÔ¬§»È…„œ‹‡†ŽÖÈÿ'
menudefaultmsg  db      'ý¥­¦½¬­®©½¤¼ÈýÔ¬§»È…„œ‹‡†ŽÖÈÿ'
menuitemmsg     db      'ý¥­¦½¡¼­¥ÈýÔ¬§»È…„œ‹‡†ŽÈÅÈ‹š‰›€ŒÈŸœ€È¬§»¬©¼©ÈßÆØÛÉÖÈÿ'
submenumsg      db      'ý»½ª¥­¦½ÈýÔ¬§»È…„œ‹‡†ŽÖÈÿ'
illegalmsg      db      'ýª’’ý’’ÆÆÆ†š‹‡†’ŒÈ‹‡……‰†ŒÆÆÆÈÿ'
questionmsg     db      'ý×ÿ'
devicemsg       db      'ý¬­¾¡«­ÈÈÈ','ÈÈÈ','ÿ'
buffersmsg      db      'ýª½®®­º»ÈÈ','ÈÈÈ','ÿ'
countrymsg      db      'ý«§½¦¼º±ÈÈ','ÈÈÈ','ÿ'
devicehighmsg   db      'ý¬­¾¡«­ ¡¯ ÈÈ','ÿ'
dosmsg          db      'ý¬§»ÈÈ','ÈÈÈ','ÈÈÈÈ','ÿ'
driveparmmsg    db      'ý¬º¡¾¸©º¥È','ÈÈÈ','ÿ'
fcbsmsg         db      'ý®«ª»È','ÈÈÈÈ','ÈÈÈ','ÿ'
filesmsg        db      'ý®¡¤­»ÈÈÈ','ÈÈÈÈ','ÿ'
installmsg      db      'ý¡¦»¼©¤¤ÈÈ','ÈÈÈ','ÿ'
installhighmsg  db      'ý¡¦»¼©¤¤ ¡¯ È','ÿ'
lastdrivemsg    db      'ý¤©»¼¬º¡¾­ÈÈÈ','ÿ'
numlockmsg      db      'ý¦½¥¤§«£ÈÈ','ÈÈÈ','ÿ'
shellmsg        db      'ý» ­¤¤È','ÈÈ','ÈÈÈÈ','ÿ'
stacksmsg       db      'ý»¼©«£»ÈÈÈ','ÈÈÈ','ÿ'
switchesmsg     db      'ý»¿¡¼« ­»È','ÈÈÈ','ÿ'
remmsg          db      'ýº­¥ÈÈ','ÈÈÈ','ÈÈÈÈ','ÿ'
breakmsg        db      'ýªº­©£ÈÈ','ÈÈ','ÈÈÈ','ÿ'
setmsg          db      'ý»­¼È','ÈÈ','ÈÈ','ÈÈÈÈ','ÿ'

lsd_msg            db   '¼€ÈÇªÈ‡˜œ‡†ÈŽ‡†ŒÈÅÈ„‰›œÈ‹‡†Žš‰œ‡†ÈÇ»È‡˜œ‡†È€‰›ÈŠ†È†‡šŒÆ',10,'ÿ'
mois_text          db   '¢‰†‰š‘ÄÈÈ®Šš‰š‘ÄÈ¥‰š‹€ÄÈÅÈÈ©˜š„ÄÈÅÈÈ¥‰‘ÄÅÈÈÅÈÈ¢†ÄÈÈÅÈÈ¢„‘ÄÈÈÅÈÈ©›œÄÈÅÈ»˜œ…ŠšÄ§‹œ‡ŠšÄÅÈ¦‡ž…ŠšÄÈ¬‹…ŠšÄÈ',0
semaine_text       db   '»†Œ‰‘ÄÈÅÈ¥‡†Œ‰‘ÄÅÈÈ¼›Œ‰‘ÄÈÈ¿Œ†›Œ‰‘Ä¼€š›Œ‰‘ÄÈ®šŒ‰‘ÄÈÅÈ»‰œšŒ‰‘ÄÈ',0
stack_error_msg    db 7,'ýŒ«šœ‹‰„È­šš‡šÉýÒÈý©½¼§«§¦®ýÈŸ‰›È†‰Š„Èœ‡ÈŽ†ŒÈ†‡€È›˜‰‹Èœ‡È‰ŒŒ',10
                   db   'þÈu‰È»­¼È«§¦®ÕÆÆÆÈ„†Èœ‡Èœ€È«§¦®¡¯Æ»±»È†‡ŸÈ†È……‡š‘Æ',10
                   db   'þÈuÀ¼€›È›È‰È†ŸÈŽ‰œšÈ‡ŽÈý©½¼§«§¦®ýÆÁ',10
                   db   'þÈu¼€È‰‹œ‰„È›˜‰‹È›È‡ŽÈÿ'
stack_error_msg2   db   'ÈŠ‘œ›ÓÈ‘‡È†ŒÈ‰œÈ„‰›œÈÿ'
stack_error_msg3   db   'ÈŠ‘œ›Æ',10
                   db   '«‡šš‹œÈœ€›Èšš‡šÈŠ‘È‰ŒŒ†È‰†‘ÈœœÈ‡šÈ›˜‰‹›Èœ‡Èœ€È¬­¾¡«­ÕÌÈ„†È†È‘‡š',10
                   db   '«§¦®¡¯Æ»±»ÈŽ„ÆÈ­ÒÈ¬­¾¡«­ÕÌÈ‰†‘ÈœœÈ˜„‰‹ŒÈ€šÉ',10
                   db   'þÈ€ÔÅÅÅÅÈÈÚÛÈŠ‘œ›ÉþÅjÖ',10
                   db   '¦‡œÒÈšš‡š›È…‰‘È‡‹‹šÈŒš†Èœ€›ÈŠ‡‡œÆ',10,'ÿ'

timer_error_msg db      7,'ýŒ­šš‡šýÒÈœ€È˜‰š‰…œšÈ›˜‹ŽŒÈŸœ€Èœ€ÈÇ¼È‡˜œ‡†È›È†ž‰„ŒÒÈÇ¼ÿ'
custom_msg_error_a db 7,'ýŒ­šš‡šýÒÈŠ‰ŒÈ‡˜œ‡†È†Èœ€È«§¦®¡¯Æ»±»ÒÈÇ¥ÿ'

custom_msg_error_b db 10,'±‡È€‰žÈ›˜‹ŽŒÈ‰†È†‹‡šš‹œÈž‰„ÈŸœ€Èœ€ÈÇ¥³µÈ‡˜œ‡†ÄÈœ€È‡†„‘',10
		   db '‰„„‡ŸŒÈ‡†›È‰šÒþÈpÙÈÒÈ…‡š††È…››‰',10
		   db 'þÈÚÈÒÈŒ‰‘È…››‰',10
		   db 'þÈÛÈÒÈž††È…››‰',10
		   db 'þÈÜÈÒÈ†€œÈ…››‰',10
		   db '®‡šÈ…‡šÈ†Ž‡š…‰œ‡†ÄÈ‹‡†›„œÈœ€È…‰†‰„È‡ŽÈý©½¼§«§¦®Æý',10,'ÿ'
                                                                                                   
msg_mon  db   'üý!Èýýºý­ý©ý¬ýÈÙÆØØÈþ%v#þ%S',10 
        db      'RýÈÙÙÄÈ‹€ÆÈŒÈ„‰È«„‰šbšÈÈÈý2,,8,,,WýÈ©½¼§«§¦®Æ»±»ÒýÈ…„œ˜„È‹‡†Žš‰œ‡†›ÈÈý$%S',10 
        db      'RýÈÙÚØßÈ¯†ž‰È»Ÿœ’š„‰†ŒÈý2,),,,,WÈ[ýÈžÆÈÅÕÅÕÅÕÅÕÅÕÅÕÅÕÅÕÈÅÕÅÕÅÈÕÅÕÅÕÈÅÕÅÕÅÈÕÅÈýRÈR',10 
	db      'RýÈÀØÚÚÁÈßÛÝÈÞÑÈÜßþÈmý[ýƒÈ¬Æ¬ÆÈý+W.þ%ŒQÈR',10 
	db      '$þ%}]È24,,W+)1ýÈª©«£»¸©«­ýÈ…‰†‰„þÈzýÈRÈR',10 
        db      'RýÈ¬‡Šš‡žƒ†È¬‰†„ÈÀ‹ÁÈÈý(,)7,:)1ýÈÈÈ»¸©«­ýÈ„›œÈ‡ŽÈ‹‡†Žš‰œ‡†›þÈnýÈRÈR',10  
	db      ' %#þ%€"þ%TÈR',10
        db      'ÈÈ þ%y,,ýƒÈ»Æ¼Æ¡ÆýÈ,,þ%ŽT',10,'ÿ'
                                                                                                   
reenable_msg1   db      'ýýÈÈÈ¬ž‹È³ý¬ýµÈÅÈ¬ž‹€€È³ý½ýµÈÅÈ¡†›œ‰„„È³ý¡ýµÈÅÈ¡†›œ‰„„ €È³ý¿ýµÈÅÈ»€„„È³ý»ýµÈÈÈýÿ'
reenable_msg2   db      'ýýÈÈº…È³ýØýµÈÅÈ»œÈ³ý¾ýµÈÅÈ®„›È³ý®ýµÈÅÈ¤‰›œŒšžÈ³ý¤ýµÈÅÈ¦…„‡‹ƒÈ³ý¦ýµÈÅÈ«‡†œš‘È³ý¹ýµÈÈýÿ'
reenable_msg3   db      'ýýþÈlªŽŽš›È³ýªýµÈÅÈªš‰ƒÈ³ý«ýµÈÅÈ¬šž˜‰š…È³ý¸ýµÈÅÈ»œ‰‹ƒ›È³ý£ýµÈÅÈ®‹Š›È³ý°ýµþÈkýÿ'

sw_err_switch   db      'ýŒ­šš‡šýÒÈŠ‰ŒÈ‡˜œ‡†È†È«§¦®¡¯Æ»±»ÒÈÇÿ'
passage_msg     db      10,'ÿ'                
spassage_msg    db      'ÈÈÈÿ'                
sw_err_msg      db      7,10
		db      '±‡È€‰žÈ›˜‹ŽŒÈ‰†È†ž‰„ŒÈ‡˜œ‡†ÈÀ›ÁÈ†Èœ€È«§¦®¡¯Æ»±»ÈŽ„ÈŽ‡šÈý©½¼§«§¦®Æý',10
                db      '¼€È‡†„‘Èž‰„ŒÈ‡†›È‰šÒÈÇ¬ÈÇ­ÄÇ¢³¬µ³«µÄÇ¦ÄÇ¸ÄÇ»ÄÇ«ÄÇ¯ÄÇ£ÄÇ¥³µÈ‰†ŒÈÇ¼Æ',10
		db      '®‡šÈ‰È…‡šÈŒœ‰„ŒÈ†Ž‡š…‰œ‡†È‹‡†›„œÈœ€È…‰†‰„È‡ŽÈý©½¼§«§¦®Æý',10,'ÿ'

err_msg_new     db      7,'ýŒ­šš‡šýÒÈ‹‡†Žš‰œ‡†Èÿ' 

err_msg_old     db      'ÈŒ‡›È†‡œÈ›œÆÆÆ',10
		db      10
		db      'ý©½¼§«§¦®ýÈŸ‰›È†‡œÈ‰Š„Èœ‡ÈŽ†ŒÈœ€È‹‡†Žš‰œ‡†È‘‡È€‰žÈ‚›œÈ‹€‡›†É',10
		db      '­œ€šÈ‘‡È€‰žÈ˜š››ŒÈœ€ÈŸš‡†Èƒ‘ÄÈ‡šÈœ€È‹‡†Žš‰œ‡†ÈŒ‡›È†‡œÈ›œÆ',10
		db      '«€‡‡›È‰†‡œ€šÈ‹‡†Žš‰œ‡†ÆÈ«€‹ƒÈœ€‰œÈ‘‡È€‰žÈ‰ÈŒŽ‰„œÈ‹‡†Žš‰œ‡†',10
                db      '†Èœ€È«§¦®¡¯Æ»±»ÈŽ„ÉþÈŒ',10
                db      'ýŒ©œœ†œ‡†ÉýÈº…‡žÈ‰†‘È˜‰šœÈ‡ŽÈ…„œ˜„È‹‡†Žš‰œ‡†›È‡ŽÈ¬§»ÈÞÆÉý',10,'ÿ'

msg_err_dollar  db      7,'ýŒ­šš‡šýÈ†Èœ€È«§¦®¡¯Æ»±»É',10
		db      10
		db      '±‡ÈŽ‡š‡œÈœ€È¬­¾¡«­ÕÌÈ„†È‰ŽœšÈœ€È„‰›œÈ‹‡†Žš‰œ‡†È†Èœ€È«§¦®¡¯Æ»±»É',10
		db      '¸š››Èª©«£»¸©«­Èœ‡È‹‡†›„œÈœ€È…‰†‰„È‡ŽÈý©½¼§«§¦®ýÈ‡šÈ‰†‘Èƒ‘Èœ‡È‹‡†œ†Æ',10
                db      10
                db      'ýŒ©œœ†œ‡†ÉýÈ¡ŽÈ‘‡È‰šÈ›šÈœ€‰œÈœ€È¬­¾¡«­ÕÌÈ„†È›È˜š›†œÈ†È‘‡šÈ«§¦®¡¯Æ»±»',10
                db      'Ž„ÄÈŒ‡È‹€‹ƒÈŽ‡šÈ‰†‘È„…†œÈ‡ŽÈ…„œ˜„È‹‡†Žš‰œ‡†›È‡ŽÈ¬§»ÈÞÆÄÈŽÈŽ‡†ŒÄ',10
                db      'š…‡žÈœ€…ÆÈ¼€È³‹‡……‡†µÈ„†È›Èœ€È…‡›œÈŽš™†œÈ‹‰›È‡ŽÈœ€›Èšš‡šÆý',10
		db      10,'ÿ'

msg_reboot_6    db      '¸š››ÈºÈœ‡ÈšŠ‡‡œÈ‘‡šÈ‹‡…˜œšÆÈ»†‹È‘‡È‰šÈ›†È¬§»ÈÞÆ°Èžš›‡†ÄÈ›',10
		db      '®ÝÈ‰†ŒÈ®ÐÈƒ‘›Èœ‡È›ƒ˜Èœ€È„‡‰Œ†È‡ŽÈý©½¼§«§¦®ýÈ‰†ŒÈ‹‡šš‹œÈœ€È˜š‡Š„…ÈŸœ€',10
		db      '‰ÈœœÈŒœ‡šÈ„‰œšÆ',10
                db      '®‡šÈ…‡šÈ†Ž‡š…‰œ‡†È‡†È®ÝÈ‰†ŒÈ®ÐÈƒ‘›ÈŽ†‹œ‡†ÄÈ‹‡†›„œÈœ€È…‰†‰„È‡Ž',10   
		db      '¥›‹š‡›‡ŽœÈ¥»È¬§»ÈÀºÁÆ',10
		db      10
		db      '¸š››È‰†‘Èƒ‘Èœ‡È‹‡†œ†Èœ€ÈŠ‡‡œ˜È‡ŽÈ‘‡šÈ‹‡…˜œšÈ‰†ŒÈ†ŒÈ©½¼§«§¦®Æ»±»',10
		db      '€šÆÈ«‡šš‹œÈœ€È˜š‡Š„…ÈŸœ€È‰ÈœœÈŒœ‡šÈ„‰œšÆ',10,'ÿ'
		
msg_reboot_not6 db      '¸š››È‰†‘Èƒ‘Èœ‡È‹‡†œ†Èœ€È‹œ‡†È‡ŽÈœ€È«§¦®¡¯Æ»±»ÈŽ„È‰†ŒÈ†Œ',10
		db      'ý©½¼§«§¦®ýÈ€šÆÈ«‡šš‹œÈœ€È˜š‡Š„…ÈŸœ€È‰ÈœœÈŒœ‡šÈ„‰œšÆ',10,10
		db      '¸š››ÈºÈœ‡ÈšŠ‡‡œÈ‘‡šÈ‹‡…˜œšÆÈ½›È‰ÈŠ‡‡œÈŒ›ƒÈœ‡È›ƒ˜Èœ€È‹œ‡†È‡Ž',10
		db      'ý©½¼§«§¦®ÆýÈ¼€†È‹‡šš‹œÈœ€È˜š‡Š„…ÈŸœ€È‰ÈœœÈŒœ‡šÆ',10,'ÿ'

msg_choosec     db      '«€‡‡›È‰È‹‡†Žš‰œ‡†È‘‡ÈŸ‰†œÈœ‡È„‡‰ŒÈ‚›œÈŠ‘È˜š››†È‰Èƒ‘Æ',10
		db      'ÈÈÈÈÄÈ¸½˜ÄÈ¸¬†ÄÈ ‡…È‡È­†ŒÈŸ„„È…‡žÈ†Èœ€È„›œÆÆÆ',10 
                db      '»¼©ºþÈs†ŒÈý©½¼§«§¦®ýÈ€šÓ',10
		db      '­¦¼­ºÈ‡šÈ»¸©«­þÈi„‡‰Œ›Èœ€È‹‡†Žš‰œ‡†È‡†ÈŸ€‹€Èœ€È‹š›‡šÈ›È†‡ŸÓ',10
		db      '¼©ªþÈt›Èœ€È‹‡†Žš‰œ‡†Èœ›„ŽÓ',10
		db      'ª©«£»¸©«­þÈn›€‡Ÿ›Èœ€È…‰†‰„È‡ŽÈý©½¼§«§¦®Æý',10,10,'ÿ'

error_last_msg  db    7,'¼€È‹‡†Žš‰œ‡†È›˜‹ŽŒÈ†Èœ€È©½¼§«§¦®Æ¬©¼ÈŽ„È›È†‡œÈž‰„ŒÆ',10
                db      '±‡È€‰žÈ˜š‡Š‰Š„‘È›˜‹ŽŒÈ‰†È†ž‰„ŒÈ‹‡†Žš‰œ‡†ÈŸœ€Èª§§¼¡¼Æ',10
                db      '®‡šÈ…‡šÈ†Ž‡š…‰œ‡†È‡†Èœ€È©½¼§«§¦®Æ¬©¼ÈŽ„ÄÈ˜„‰›È‹‡†›„œÈœ€È…‰†‰„Æ',10,'ÿ'

special_error_msg       db    7,10,'ýŒ­šš‡šýÒÈ«§¦®¡¯Æ»±»ÉÈ‘‡È€‰žÈ†‡È‹‡†Žš‰œ‡†›È›˜‹ŽŒÉ',10
			db      'þÈl¸š››È‰†‘Èƒ‘Èœ‡Èœš…†‰œÈ©½¼§«§¦®ÆÆÆ',10,'ÿ'

error_creating          db      7,10,'ýŒ­šš‡šýÒÈ‹š‰œ†È©½¼§«§¦®Æ¬©¼ÈŽ„É',10,'ÿ'
error_opening           db      7,10,'ýŒ­šš‡šýÒÈ‡˜††È©½¼§«§¦®Æ¬©¼ÈŽ„ÉÈÀ†‡†È‹šœ‹‰„Èšš‡šÁ',10,'ÿ'
error_closing           db      7,10,'ýŒ­šš‡šýÒÈ‹„‡›†È©½¼§«§¦®Æ¬©¼ÈŽ„É',10,'ÿ'
error_readwrite         db      7,10,'ýŒ­šš‡šýÒÈš‰Œ†È‡šÈŸšœ†È©½¼§«§¦®Æ¬©¼ÈŽ„É',10,'ÿ'
j_error_msg             db      7,10,'ýŒ­šš‡šýÒÈœ€ÈÇ¢È‡˜œ‡†ÈŒ‡›È†‡œÈ€‰žÈœ€È›‰…È˜‰š‰…œš›È‰›Èœ€È˜šž‡›',10
                        db      'žš›‡†È‡ŽÈ©½¼§«§¦®ÄÈ†ŸÈ›‘†œ‰Ò',10
                        db      'ýÇ¢ý³ý¬ýµ³ý«ýµÄÈŸ€š',10
                        db      'ý¬ýÒÈ‰„Ÿ‰‘›È›€‡ŸÈœ€È„›œÈ†ŒšÈ¬§»ÈŠ„‡ŸÈßÆØØ',10
                        db      'ý«ýÒÈ‰„Ÿ‰‘›È›€‡ŸÈœ€È„›œÈ†ŒšÈ¬§»ÈßÆØØÈ‰†ŒÈ‰Š‡žÈÀ¿†Œ‡Ÿ›ÈÑÝÁÆ',10,'ÿ'
kbd_extraparam          db      7,10,'ýŒ­šš‡šýÒÈ…‡šÈœ€‰†È‡†Èƒ‘Š‡‰šŒÈ€‰›ÈŠ†È›˜‹ŽŒÈ›†ÈÇ£É',10
			db      '¼€ÈŽš›œÈ˜‰š‰…œšÈ‡†„‘ÈŸ„„ÈŠÈ›ŒÄÈœ€Èš›œÈŸ„„ÈŠÈ†‡šŒÆ',10,'ÿ'
kbd_invalidparam        db      7,10,'ýŒ­šš‡šýÒÈ†ž‰„ŒÈ˜‰š‰…œšÈŸœ€ÈÇ£É',10
			db      '¼€È‡†„‘Èž‰„ŒÈ‡˜œ‡†›È‰šÒ',10
			db      '2þ,†*þ,†W',10 
			db      '[Èª„…þÈzýª­ýÈÈ[Èªš›„þÈ{ýªºýÈÈ[',10
			db      '[È«‰†‰Œ‰ÈÀŽš†‹€ÁþÈrý«®ýÈÈ[È¼‹€‹‡›„‡ž‰ƒ‰ÈÈÀœ‹€™ÁÈÈÈÈý«²ýÈÈ[',10
			db      '[È¼‹€‹‡›„‡ž‰ƒ‰ÈÈÀ›„‡ž‰ƒÁþÈiý»¤ýÈÈ[È¬‰†…‰šƒþÈyý¬£ýÈÈ[',10
			db      '[È®†„‰†ŒþÈzý»½ýÈÈ[È®š‰†‹þÈ{ý®ºýÈÈ[',10
			db      '[È¯š…‰†‘þÈzý¯ºýÈÈ[È †‰š‘þÈzý ½ýÈÈ[',10
			db      '[È¡œ‰„‘þÈ|ý¡¼ýÈÈ[È¤‰œ†È‰…š‹‰þÈtý¤©ýÈÈ[',10
			db      '[È ‡„„‰†ŒþÈzý¦¤ýÈÈ[È¦‡šžþÈzý¦§ýÈÈ[',10
			db      '[È¸‡„‰†ŒþÈ{ý¸¤ýÈÈ[È¸‡šœ‰„þÈyý¸§ýÈÈ[',10
			db      '[È»˜‰†þÈ|ý»¸ýÈÈ[È»ŸŒ†þÈzý»¾ýÈÈ[',10
			db      '[È»Ÿœ’š„‰†ŒÈÀŽš†‹€ÁþÈmý»®ýÈÈ[È»Ÿœ’š„‰†ŒÈÀš…‰†ÁþÈmý»¯ýÈÈ[',10
			db      '[È¯š‰œÈªšœ‰†þÈtý½£ýÈÈ[È«š‡‰œ‰Ç»šŠ‰Ç»„‡ž†‰þÈjý±½ýÈÈ[',10
			db      '+þ,†)þ,†\',10 
			db      '[þÈu¼€Èý½»ýÈƒ‘Š‡‰šŒÈ›Èœ€ÈŒŽ‰„œÈ‡†ÆþÈu[',10
			db      '(þ,©1',10,'ÿ'
running_chicago_message db      'ü2Èý©½¼§«§¦®ÈŽ‡šÈ¿†Œ‡Ÿ›ÈÑÝÉÄÈŽ†‰„È‰›œÈÙÑÑÝÈýþ,|W',10 
			db      '[ÈýÈ¬§»ÈßÆØØÈ‡šÈ‰Š‡žÈ€‰›ÈŠ†ÈŒœ‹œŒÆÆÆÈÈýþÈ[',10
                        db      '[ÈÈý©½¼§«§¦®ýÈŸ„„È›Èœ€ÈŒŽ‰„œÈ‹‡†Žš‰œ‡†È‡ŽÈý¿†ÈÑÝÉýÈÀÇ ÁþÈj[',10
			db      '(þ,©1',10,'ÿ'
warning_chicago         db      '2Èý©½¼§«§¦®ÈŽ‡šÈ¿†Œ‡Ÿ›ÈÑÝÉÄÈŽ†‰„È‰›œÈÙÑÑÝÈýþ,|W',10 
                        db      '[ÈýÈ©Èžš›‡†È‡ŽÈ¬§»È‰Š‡žÈßÆØØÈ€‰›ÈŠ†ÈŒœ‹œŒÆÆÆþÈnýþÈm[',10
			db      '[ÈÈ¼€›Èžš›‡†È‡ŽÈý©½¼§«§¦®ýÈ€‰›È†‡œÈŠ†Èœ›œŒÈŸœ€Èœ€›Èžš›‡†È‡ŽÈÈ[',10
                        db      '[ÈÈ¬§»ÆÈ¼€‰œÈŒ‡›È†‡œÈ…‰†ÄÈœ€‰œÈ‰†‘È˜š‡Š„…›È¿¡¤¤È‡‹‹šÄÈ›†‹þÈk[',10
                        db      '[ÈÈý©½¼§«§¦®ýÈ›˜˜‡šœ›È¿†ÈÑÝÄÈŠœÈ‘‡È›€‡„ŒÈœÈœ€È„‰œ›œÈžš›‡†ÉÈÈÈ[',10
			db      '(þ,©1',10,'ÿ'
skiping_message         db      'ý©½¼§«§¦®ýÈ›ƒ˜›È†‡š…‰„È‹‡†Žš‰œ‡†›È†È«§¦®¡¯Æ»±»ÆÆÆ',10,'ÿ' 
dos_five_set            db      '¬§»ÈÝÆØÈ‡šÈŠ„‡ŸÈŒœ‹œŒÉÈ¸„‰›È‰ŒŒÈÇ¾ÈÀŒ›‰Š„Èº­©¬ÁÈÅÈ›Èº­©¬«§¦®Æ­°­É',10,'ÿ'
msg_matin_bonheur       db      'ü¿‡ƒÈ˜È‰š„‘Èœ€›È…‡š††×',10,'ÿ'
                        db      500 dup (?)
msg_stop_working        db      'ü»œ‡˜Èœšš‡š’†È‘‡šÈ‹‡…˜œšÈ‰œÈ†€œÉ',10,'ÿ'
                        db      500 dup (?)
msg_soir                db      'ü¯‡‡ŒÈž††ÆÆÆ',10,'ÿ' 
                        db      500 dup (?)
msg_matin               db      'ü ÈŒŒÆÆÆ',10,'ÿ'
                        db      500 dup (?)
DOSError1       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ» ©º­È†‡œÈ†›œ‰„„ŒÈÉ',10,'ÿ'
DOSError2       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ®„È†‡œÈŽ‡†ŒÈÉ',10,'ÿ'
DOSError3       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¸‰œ€È†‡œÈŽ‡†ŒÈ‡šÈŽ„ÈŒ‡›†''œÈ›œÉ',10,'ÿ'
DOSError4       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¦‡È…‡šÈŽšÈ€‰†Œ„›É',10,'ÿ'
DOSError5       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ©‹‹››ÈŒ†ŒÉ',10,'ÿ'
DOSError6       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¡†ž‰„ŒÈŽ„È€‰†Œ„È‡šÈŽ„È†‡œÈ‡˜†ÈÉ',10,'ÿ'
DOSError7       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¥…‡š‘ÈŠ„‡‹ƒÈŸ‰›ÈŒ›œš‡‘ŒÈÉ',10,'ÿ'
DOSError8       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¡†›ŽŽ‹†œÈ……‡š‘È„ŽœÈÉ',10,'ÿ'
DOSError9       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¥…‡š‘ÈŠ„‡‹ƒÈŸ‰›È¦§¼È‰„„‡‹‰œŒÉ',10,'ÿ'
DOSError12      db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ«‰†''œÈ›Èœ€›È‰‹‹››È…‡ŒÈÉ',10,'ÿ'
DOSError14      db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¡†ž‰„ŒÈ›ƒÈŒ›œ‰†‹É',10,'ÿ'

DataError       db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ¬‰œ‰È†ÈŽ„È›È†ž‰„ŒÈÉ',10,'ÿ'
DefaultError    db      '©½¼§«§¦®ÒÒ¤§§¥ÒÒ½†ŒŽ†ŒÈšš‡šÈšš‡šÈÉ',10,'ÿ'
