 ═══════ MULTIPLE CONFIGURATIONS!═══════════
 -- A Stolen Technologies Inc. Software ----
 <=========================================>
 <------- AUTOCONF, version 3.00! (beta 2)->
 ════════════ ENGLISH VERSION ══════════════ 
 The ever best multiple configs software!
 # AUTOCONF 3.00.00 (beta 2)
        iLINE 1.10 corrected bugs!
        iREAD 1.00
        iLOOM 0.00 under construction.
 # DOS2ACF & ACF2DOS 1.40
 # UNRF QEMM un /RF 1.32
 # BOOTIT 1.5
 # READCONF 4.0 (iREAD for DOS 5 and below)
 ══════════ Made in Switzerland ! ══════════
